import sanitizeHtml from "sanitize-html";

const allowedTags = [
  "a",
  "blockquote",
  "br",
  "code",
  "dd",
  "details",
  "div",
  "dl",
  "dt",
  "em",
  "figcaption",
  "figure",
  "h2",
  "h3",
  "h4",
  "hr",
  "img",
  "li",
  "ol",
  "p",
  "span",
  "strong",
  "summary",
  "table",
  "tbody",
  "td",
  "th",
  "thead",
  "tr",
  "ul",
  "video",
  "source",
];

const allowedClasses = [
  "bg-amber-50",
  "bg-blue-50",
  "bg-green-50",
  "bg-red-50",
  "bg-slate-50",
  "bg-teal-50",
  "border",
  "border-amber-100",
  "border-blue-100",
  "border-green-100",
  "border-red-100",
  "border-slate-100",
  "border-teal-100",
  "demo-callout",
  "demo-callout-grid",
  "demo-case-study",
  "demo-caption",
  "demo-clinical-card",
  "demo-diagram",
  "demo-eyebrow",
  "demo-expandable",
  "demo-hero-block",
  "demo-hotspot",
  "demo-hotspots",
  "demo-image-left",
  "demo-image-panel",
  "demo-image-right",
  "demo-image-zoom",
  "demo-learning-card",
  "demo-pill",
  "demo-principle-card",
  "demo-procedure",
  "demo-scenario",
  "demo-slide",
  "demo-stat",
  "demo-tab-active",
  "demo-tab-content",
  "demo-tab-list",
  "demo-tabbed-row",
  "demo-video-block",
  "demo-video-player",
  "demo-video-screen",
  "demo-warning",
  "font-semibold",
  "mb-2",
  "mb-3",
  "mb-4",
  "mt-2",
  "mt-3",
  "mt-4",
  "p-4",
  "rounded-lg",
  "text-amber-900",
  "text-blue-900",
  "text-green-900",
  "text-red-900",
  "text-slate-600",
  "text-slate-700",
  "text-slate-800",
  "text-teal-700",
  "text-teal-900",
  "underline",
];

export function sanitizeLearningHtml(html: string) {
  return sanitizeHtml(html, {
    allowedTags,
    allowedAttributes: {
      a: ["href", "target", "rel", "class"],
      div: ["class", "role", "aria-label"],
      img: ["src", "alt", "width", "height", "class", "loading"],
      p: ["class"],
      span: ["class"],
      source: ["src", "type"],
      strong: ["class"],
      em: ["class"],
      ul: ["class"],
      ol: ["class"],
      li: ["class"],
      h2: ["class"],
      h3: ["class"],
      h4: ["class"],
      details: ["class", "open"],
      summary: ["class"],
      figure: ["class"],
      figcaption: ["class"],
      table: ["class"],
      thead: ["class"],
      tbody: ["class"],
      tr: ["class"],
      th: ["class", "scope"],
      td: ["class"],
      video: [
        "src",
        "class",
        "controls",
        "preload",
        "poster",
        "aria-label",
        "playsinline",
      ],
    },
    allowedClasses: {
      "*": allowedClasses,
    },
    allowedSchemes: ["http", "https", "mailto"],
    allowedSchemesByTag: {
      img: ["http", "https", "data"],
      video: ["http", "https", "data"],
      source: ["http", "https", "data"],
    },
    transformTags: {
      a: sanitizeHtml.simpleTransform("a", { rel: "noopener noreferrer" }),
      img: sanitizeHtml.simpleTransform("img", { loading: "lazy" }),
    },
  });
}
